version: '3'
 
services:
#    redis1:
#      image: bitnami/redis-cluster:6.2
#      environment:
#        - "ALLOW_EMPTY_PASSWORD=yes"
#        - "REDIS_CLUSTER_REPLICAS=1"
#        - "REDIS_NODES=redis1 redis2 redis3 redis4"
#    redis2:
#      image: bitnami/redis-cluster:6.2
#      environment:
#        - "ALLOW_EMPTY_PASSWORD=yes"
#        - "REDIS_CLUSTER_REPLICAS=1"
#        - "REDIS_NODES=redis1 redis2 redis3 redis4"
#    redis3:
#      image: bitnami/redis-cluster:6.2
#      environment:
#        - "ALLOW_EMPTY_PASSWORD=yes"
#        - "REDIS_CLUSTER_REPLICAS=1"
#        - "REDIS_NODES=redis1 redis2 redis3 redis4"
#    redis4:
#      image: bitnami/redis-cluster:6.2
#      environment:
#        - "ALLOW_EMPTY_PASSWORD=yes"
#        - "REDIS_CLUSTER_REPLICAS=1"
#        - "REDIS_NODES=redis1 redis2 redis3 redis4"
#        - "REDIS_CLUSTER_CREATOR=yes"
#      ports:
#        - "6379:6379"
#      depends_on:
#        - redis1
#        - redis2
#        - redis3

    pos1:
        build: .
        cpu_count: 1
        ports: 
          - "8081:8080"
        extra_hosts:
          - "host.docker.internal:host-gateway"
    pos2:
        build: .
        cpu_count: 1
        ports: 
          - "8082:8080"
        extra_hosts:
          - "host.docker.internal:host-gateway"
    pos3:
        build: .
        cpu_count: 1
        ports: 
          - "8083:8080"
        extra_hosts:
          - "host.docker.internal:host-gateway"
    pos4:
        build: .
        cpu_count: 1
        ports: 
          - "8084:8080"
        extra_hosts:
          - "host.docker.internal:host-gateway"

    haproxy:
        build: ./haproxy
        ports:
          - "8080:8080"
        extra_hosts:
          - "host.docker.internal:host-gateway"